
project_id = "khxfqyhykmzcqdgjdcbd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"
port = 54324
max_header_length = 4096

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54326
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_anonymous_sign_ins = false

[functions.create-mercadopago-payment]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[edge-runtime]
enabled = true
port = 54329

[analytics]
enabled = false
port = 54327
vector_port = 54328
