// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khxfqyhykmzcqdgjdcbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoeGZxeWh5a216Y3FkZ2pkY2JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMTYwMzYsImV4cCI6MjA2NzU5MjAzNn0.GkTur54MC85TGYFlSwZ2aDOf2Ouh3qsLdVxcPyArsn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});